# Site settings
name: akkudu.com
title: Andaç Karay Kudu ~ Think Simple, Make Incredible | akkudu.com/blog
description: "Andaç Karay Kudu - Consultant, Coach, Mentor, Trainer, Pair Programmer"
baseurl: "/"
url: "http://akkudu.com"
email: hey@akkudu.com

exclude: ['Gemfile.lock', 'Gemfile']

gems: ['github-pages']

# Build settings
markdown: kramdown
permalink: pretty
